package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MarkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarkAllPropertiesEquals(Mark expected, Mark actual) {
        assertMarkAutoGeneratedPropertiesEquals(expected, actual);
        assertMarkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarkAllUpdatablePropertiesEquals(Mark expected, Mark actual) {
        assertMarkUpdatableFieldsEquals(expected, actual);
        assertMarkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarkAutoGeneratedPropertiesEquals(Mark expected, Mark actual) {
        assertThat(actual)
            .as("Verify Mark auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarkUpdatableFieldsEquals(Mark expected, Mark actual) {
        assertThat(actual)
            .as("Verify Mark relevant properties")
            .satisfies(a -> assertThat(a.getScore()).as("check score").isEqualTo(expected.getScore()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarkUpdatableRelationshipsEquals(Mark expected, Mark actual) {
        assertThat(actual)
            .as("Verify Mark relationships")
            .satisfies(a -> assertThat(a.getSubjectRegister()).as("check subjectRegister").isEqualTo(expected.getSubjectRegister()));
    }
}
