package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubjectRegisterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubjectRegisterAllPropertiesEquals(SubjectRegister expected, SubjectRegister actual) {
        assertSubjectRegisterAutoGeneratedPropertiesEquals(expected, actual);
        assertSubjectRegisterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubjectRegisterAllUpdatablePropertiesEquals(SubjectRegister expected, SubjectRegister actual) {
        assertSubjectRegisterUpdatableFieldsEquals(expected, actual);
        assertSubjectRegisterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubjectRegisterAutoGeneratedPropertiesEquals(SubjectRegister expected, SubjectRegister actual) {
        assertThat(actual)
            .as("Verify SubjectRegister auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubjectRegisterUpdatableFieldsEquals(SubjectRegister expected, SubjectRegister actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubjectRegisterUpdatableRelationshipsEquals(SubjectRegister expected, SubjectRegister actual) {
        assertThat(actual)
            .as("Verify SubjectRegister relationships")
            .satisfies(a -> assertThat(a.getStudent()).as("check student").isEqualTo(expected.getStudent()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()));
    }
}
